#!/bin/sh

printf "푸쉬 전에 build 테스트를 실행할까요? (y/n): "
read answer </dev/tty

# push 를 하면 build, test 등을 실행할 것인지, 안하고 바로 push 할 것인지 선택하게 해줍시다.
# y를 누르면 build, test 를 실행하고, n을 누르면 바로 push 합니다.



case "$answer" in
  y|Y)
    echo "Build를 실행합니다..."

    npm run build || exit 1
    npm run test || exit 1
    echo "build complete"
    echo "Build가 성공했습니다."
    ;;
  n|N)
    echo "Build를 건너뜁니다."
    ;;
  *)
    echo "y 또는 n만 입력해주세요. 푸쉬를 중단합니다."
    exit 1
    ;;
esac


printf "codex 문서 생성을 실행할 까요? (y/n): "
read answer </dev/tty


case "$answer" in
  y|Y)
    echo "codex 문서 생성을 실행합니다..."
    codex exec "해당 브랜치가 생성된 이후부터 변경된 파일들을 커밋기록을 통해 확인하고, 어떤 작업을 했는지 자세히 파악하여 dev/log/[yymmdd]_push.md 에 요약해 작성해주세요. 이미 있다면 이어서 작성하세요"
    echo "codex 문서 생성을 완료했습니다."
    echo "push를 진행합니다."
    ;;
  n|N)
    echo "codex 문서 생성을 건너뜁니다."
    ;;
  *)
    echo "y 또는 n만 입력해주세요. 푸쉬를 중단합니다."
    exit 1
    ;;
esac


# pr 곧바로 생성할 생각이 있는지 확인

printf "pr 문서 생성을 실행할까요? (y/n): "
read answer </dev/tty

case "$answer" in
  y|Y)
    echo "pr 문서 생성을 실행합니다."
    codex exec "해당 브랜치에서 수행한 내용을 확인하여 pr 문서를 작성하세요. pr 문서는 .github/workflows/pr-body.md에 작성하세요. 이미 있다면 무시하고 바로 종료하세요."
    git add .github/workflows/pr-body.md --no-verify
    git commit -m "pr 문서 작성" --no-verify
    echo "pr 문서 생성을 완료했습니다. push를 진행합니다."
    ;;
  n|N)
    echo "pr 생성을 건너뛰고 푸쉬합니다."
    ;;
  *)
    echo "y 또는 n만 입력해주세요. 푸쉬를 중단합니다."
    exit 1
    ;;
esac



exit 0